name: Go CI

on:
  push:
    branches: [ '*', '*/*' ]

jobs:

  build:
    name: Test for Go ${{ matrix.gover }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gover: ['~1.18', '~1.19', '~1.20']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.gover }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
